# Generated by Django 3.0.4 on 2020-03-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormBlueprint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workflow', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workflows.Workflow')),
            ],
        ),
    ]
