# Generated by Django 2.0 on 2020-03-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formblueprint',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='formblueprint',
            name='title',
            field=models.CharField(default='', max_length=128),
            preserve_default=False,
        ),
    ]
