# Generated by Django 2.0 on 2020-04-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forms', '0002_auto_20200322_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='formblueprint',
            name='saved',
            field=models.BooleanField(default=False),
        ),
    ]
