# Generated by Django 3.0.4 on 2020-04-10 04:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflows', '0002_employeehaspermission'),
        ('employees', '0002_role'),
        ('forms', '0003_formblueprint_saved'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormInstance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active', models.BooleanField(default=False)),
                ('blueprint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forms.FormBlueprint')),
                ('current_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Node')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Profile')),
            ],
        ),
    ]
