# Generated by Django 3.0.4 on 2020-03-10 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('teams', '0001_initial'),
        ('employees', '0002_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, unique=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assosiated_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employees.Role')),
                ('assosiated_team', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.Team')),
                ('next_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next', to='workflows.Node')),
                ('prev_node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prev', to='workflows.Node')),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflows.Workflow')),
            ],
        ),
    ]
